version: '3.8'
name: ${APP_NAME}

volumes:
  pg_data:

services:
  database:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: ${APP_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
    ports:
      - ${DB_PORT}:${DB_PORT}
    command:
      - 'postgres'
      - '-c'
      - 'wal_level=logical'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - ./database/logs:/var/log/postgresql
      - ./database/pg_data:/var/lib/postgresql/data

  # Only for self-hosted. Read more https://electric-sql.com/docs/usage/installation/postgres#self-host--run-locally
  electric:
    image: electricsql/electric
    restart: always
    depends_on:
      - database
    environment:
      # DATABASE_URL: 'postgresql://${DB_USERNAME}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}'
      DATABASE_URL: postgresql://${DB_USERNAME}:${DB_PASSWORD}@database:${DB_PORT}/${APP_NAME}
      DATABASE_REQUIRE_SSL: false
      AUTH_MODE: insecure
      LOGICAL_PUBLISHER_HOST: electric
      PG_PROXY_PORT: http # Enable migration proxy to enable electrifying of tables
      PG_PROXY_PASSWORD: ${POSTGRES_PROXY_PASSWORD}
      ELECTRIC_WRITE_TO_PG_MODE: direct_writes
      ## When AUTH_MODE is 'insecure', following is ignored.
      # AUTH_JWT_ALG: ${SYNC_SERVICE_AUTH_JWT_ALG}
      # AUTH_JWT_KEY: ${SYNC_SERVICE_AUTH_JWT_SECRET}
    ports:
      - ${ELECTRIC_PORT}:${ELECTRIC_PORT} # ElectricSQL Sync service
      - ${POSTGRES_PROXY_PORT}:${POSTGRES_PROXY_PORT} # ElectricSQL Postgres Proxy service
